### ISSUE TITLE
Thanks so much for the tool

### ISSUE THREAD

**Issue by jainbhaaniu03** [abdbbdii/hianime-to-myanimelist#2]
It's been working for me, but all of a sudden, when I run it, I get this error:

Huge, huge thanks. I was able to get about half my list, about 140 animes, into MAL, but after that, it's not been working. If you could give me any, that would be greatly appreciated.
Thanks

**Comment by abdxdev** [comment]
Sorry for the inconvenience, please fill out [This form](https://forms.gle/wsCD4ia7cwqyCiev6) and remember to NEVER share any kind of cookie on the internet. :)

**Comment by jainbhaaniu03** [comment]
Thanks, i filled out the form, please let me know if I should do anything else

**Comment by abdxdev** [comment]
Apologies for the misunderstanding earlier. Could you please fill out the form again? I need the cookie for [this tool](https://hianime-to-myanimelist.vercel.app).

By the way, automatic error detection and proper issue handling are currently under development to prevent such issues from happening in the future. ;)

**Comment by jainbhaaniu03** [comment]
Thanks for your help. I appreciate the work you guys are doing. I re-submitted the form. Please let me know if you need anything else. Thanks.

**Comment by abdxdev** [comment]
The issue has been resolved and your MyAnimeList list has been successfully populated.
